In [1]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

## Data collection and analysis

In [2]:
dataset= pd.read_csv('diabetes.csv')

In [4]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [7]:
dataset.shape

(768, 9)

In [12]:
    dataset["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [14]:
# 0--> Non-Diabetic
# 1--> Diabetic

In [15]:
dataset.groupby("Outcome").mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [16]:
x=dataset.drop(columns='Outcome',axis=1)

In [17]:
y=dataset['Outcome']

In [18]:
x,y

(     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
 0              6      148             72             35        0  33.6   
 1              1       85             66             29        0  26.6   
 2              8      183             64              0        0  23.3   
 3              1       89             66             23       94  28.1   
 4              0      137             40             35      168  43.1   
 ..           ...      ...            ...            ...      ...   ...   
 763           10      101             76             48      180  32.9   
 764            2      122             70             27        0  36.8   
 765            5      121             72             23      112  26.2   
 766            1      126             60              0        0  30.1   
 767            1       93             70             31        0  30.4   
 
      DiabetesPedigreeFunction  Age  
 0                       0.627   50  
 1                    

In [102]:
scaler=StandardScaler()

In [103]:
scaler.fit(x)

StandardScaler()

In [104]:
scaler1=scaler.transform(x)

In [105]:

scaler1

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [106]:
x=scaler1
y=y

In [107]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=.35,stratify=y,random_state=2)

In [108]:
print (x.shape,x_train.shape,x_test.shape)

(768, 8) (499, 8) (269, 8)


In [109]:
classi=svm.SVC(kernel='linear')

In [110]:
classi.fit(x_train,y_train)

SVC(kernel='linear')

In [111]:
x_train_predict =classi.predict(x_train)

In [112]:
accuracy = accuracy_score(x_train_predict,y_train)

In [113]:
accuracy

0.7775551102204409

In [114]:
xtest =classi.predict(x_test)

In [115]:
accuracy1=accuracy_score(xtest,y_test)

In [116]:
accuracy1

0.7843866171003717

In [117]:
print("the accuracy score of test data is :",accuracy1)

the accuracy score of test data is : 0.7843866171003717


# making a predictive system

In [145]:
input_data=(1,115,70,30,96,34.6,0.529,32)

In [146]:
narray=np.asarray(input_data)


In [147]:
narray

array([  1.   , 115.   ,  70.   ,  30.   ,  96.   ,  34.6  ,   0.529,
        32.   ])

In [148]:
#reshape

In [149]:
input_data_reshape= narray.reshape(1,-1)


In [150]:
input_data_reshape

array([[  1.   , 115.   ,  70.   ,  30.   ,  96.   ,  34.6  ,   0.529,
         32.   ]])

In [151]:
std_data=scaler.transform(input_data_reshape)

In [152]:
predict =classi.predict(std_data)


In [155]:
print(std_data)
print(predict)
if(predict[0]==0):
    print("the person is not diabetic ")

[[  1.    115.     70.     30.     96.     34.6     0.529  32.   ]]
[1]


In [156]:
if(predict[0]==0):
    print("the person is not diabetic ")
else:
    print("the person is diabetic")

the person is diabetic
